[package]
name = "rust-number-of-islands"
version = "0.1.0"
authors = ["Martin Krueger <martin.krueger@sabio.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
